# Chapter 4. 행렬식(Determinant)

In [1]:
import numpy as np

In [2]:
a = np.array([[5]])
np.linalg.det(a)

4.999999999999999

In [3]:
b = np.array([[3,1], [4,-2]])
np.linalg.det(b)

-10.000000000000002

In [4]:
c = np.array([[1,2,3], [-4,5,6], [7,-8,9]])
np.linalg.det(c)

240.0000000000002

### $A 와 A^T$ 의 determinant 는 같다

In [5]:
d = c.T
np.linalg.det(d)

239.99999999999997

### 행렬 B 가 정사각행렬 A 의 두행(열)을 서로 바꾸어 얻어진 행렬이라면, |B| = -|A| 이다.

In [6]:
A = np.array([[2, -1], [3,2]])
B = np.array([[3,2], [2,-1]])
print(A)
print(B)
print()
print(np.linalg.det(A))
print(np.linalg.det(B))

[[ 2 -1]
 [ 3  2]]
[[ 3  2]
 [ 2 -1]]

6.999999999999999
-6.999999999999999


In [7]:
A = np.array([[2, -1], [3,2]])
B = np.array([[-1, 2], [2,3]])
print(np.linalg.det(A))
print(np.linalg.det(B))

6.999999999999999
-7.000000000000001


### 정사각행렬 A 의 두행(열)이 일치하면 |A| = 0 이다.

In [8]:
A = np.array([[1,2,3], [-1,0,7], [1,2,3]])
print(A)
np.linalg.det(A)

[[ 1  2  3]
 [-1  0  7]
 [ 1  2  3]]


0.0

In [9]:
A = np.array([[1,2,1], [-1,0,-1], [1,2,1]])
print(A)
np.linalg.det(A)

[[ 1  2  1]
 [-1  0 -1]
 [ 1  2  1]]


0.0

### 정사각행렬 A 의 한 행(열)의 성분이 모두 0 이면 |A| = 0

In [10]:
A = np.array([[1,2,3], [4,5,6], [0,0,0]])
print(A)
np.linalg.det(A)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


0.0

### 정사각행렬 A 의 한 행을 k(상수) 배하여 얻어진 행렬을 B 라 하면 |B| = k|A| 인 관계가 성립하는 |A| 는 0 이다.

In [11]:
A = np.array([[1,2,3], [1,5,3], [2,8,6]])
B = np.array([[1,2,3], [1,5,3], [1,4,3]])  # |A| = 2 * |B|
C = np.array([[1,2,1], [1,5,1], [1,1,1]])  # |A| = 2 * 3 * |C|
print(A)
print(B)
print(C)
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(C))

[[1 2 3]
 [1 5 3]
 [2 8 6]]
[[1 2 3]
 [1 5 3]
 [1 4 3]]
[[1 2 1]
 [1 5 1]
 [1 1 1]]
0.0
0.0
0.0


### 정사각행렬 A 의 한 행의 k 배를 다른 행에 더하여 얻어진 행렬을 B 라 하면 |B| = |A| 이다.

In [12]:
A = np.array([[1,2,3], [2,-1,3], [1,0,1]])  # 2 행을 1 배 하여 1 행에 더함
B = np.array([[5,0,9], [2,-1,3], [1,0,1]]) 
print(A)
print(B)
print(np.linalg.det(A))
print(np.linalg.det(B))

[[ 1  2  3]
 [ 2 -1  3]
 [ 1  0  1]]
[[ 5  0  9]
 [ 2 -1  3]
 [ 1  0  1]]
4.000000000000001
4.0


### A 가 n 차의 삼각행렬이면 A 의 행렬식은 주대각성분의 곱과 같다.

In [13]:
A = np.array([[2,7,-3,8,3], [0,-3,7,5,1], [0,0,6,7,6], [0,0,0,9,8], [0,0,0,0,4]])
A

array([[ 2,  7, -3,  8,  3],
       [ 0, -3,  7,  5,  1],
       [ 0,  0,  6,  7,  6],
       [ 0,  0,  0,  9,  8],
       [ 0,  0,  0,  0,  4]])

In [14]:
print(np.linalg.det(A))
print()
print([x for x in np.diag(A)])

from functools import reduce
reduce(lambda x, y: x*y, [x for x in np.diag(A)])

-1295.9999999999998

[2, -3, 6, 9, 4]


-1296

In [15]:
A = np.matrix('0 1 5;3 -6 9;2 6 1')
print(A)
np.linalg.det(A)

[[ 0  1  5]
 [ 3 -6  9]
 [ 2  6  1]]


165.00000000000009

### 두행렬 A, B 가 n 차의 정사각행렬일 때 |AB| = |A||B| 이다.

In [16]:
A = np.array([[1,2], [3,4]])
B = np.array([[2,-1], [1,2]])
print(A,'\n', B)
print(np.linalg.det(np.matmul(A, B)))
print(np.linalg.det(A) * np.linalg.det(B))

[[1 2]
 [3 4]] 
 [[ 2 -1]
 [ 1  2]]
-10.000000000000002
-10.000000000000004


### 행렬 A 가 가역이면 |A|$\neq$0 이고, $|A^{-1}|$= $\frac{1}{|A|}$ 이 성립한다.

In [17]:
A = np.array([[1,2], [3,4]])
print(A)
np.linalg.inv(A)

[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
print(1 / np.linalg.det(A))
np.linalg.det(np.linalg.inv(A))

-0.4999999999999999


-0.5000000000000001

### 부분행렬

In [19]:
x = np.array([[3,1,-4],[2,5,6],[1,4,8]] , dtype = 'int')
print(x)

# 부분행렬
def partialMatrix(arr, row, col):
    row -= 1
    col -= 1
    adjointArr = np.zeros((arr.shape[0]-1, arr.shape[1]-1))
    r, c = 0, 0
    for i in range(len(arr)):
        if i != row:
            for j in range(len(arr)):
                if j != col:
                    adjointArr[r][c] = arr[i][j]
                    c += 1
            r += 1
            c = 0   
    return adjointArr

[[ 3  1 -4]
 [ 2  5  6]
 [ 1  4  8]]


In [20]:
partialMatrix(x, 1, 2)

array([[2., 6.],
       [1., 8.]])

In [21]:
partialMatrix(x, 1,1)

array([[5., 6.],
       [4., 8.]])

### 소행렬식 / 여인자


In [22]:
# 소행렬식
M11 = np.linalg.det(partialMatrix(x, 1, 1))
M11

15.999999999999998

In [23]:
# 여인자
A11 = (-1) ** (1+1) * M11
A11

15.999999999999998

In [24]:
def cofactor(partial, row, col):
    return (-1) ** (row + col) * np.linalg.det(partial)

In [25]:
cofactor(partialMatrix(x, 1, 1), 1, 1)

15.999999999999998

In [26]:
cofactor(partialMatrix(x, 1, 2), 1, 2)

-9.999999999999998

### 수반행렬(adjoint matrix, adjugate matrix)

In [27]:
import numpy as np
x = np.array([[3,-2,1],[5,6,2],[1,0,-3]])

def adjoint_maxtix(x):
    n = x.shape[0]  
    c = np.array([[i for i in range(n)] for j in range(n)], dtype='float32')  # 수반행렬
    for i in range(n):
        for j in range(n):
            c[i][j] = cofactor(partialMatrix(x, i+1, j+1), i+1, j+1)
    return c.T

In [28]:
x

array([[ 3, -2,  1],
       [ 5,  6,  2],
       [ 1,  0, -3]])

In [29]:
partialMatrix(x, 1, 1)

array([[ 6.,  2.],
       [ 0., -3.]])

In [30]:
cofactor(partialMatrix(x, 1, 1), 1, 1)

-17.999999999999996

In [31]:
adjoint_maxtix(x)

array([[-18.,  -6., -10.],
       [ 17., -10.,  -1.],
       [ -6.,  -2.,  28.]], dtype=float32)

In [32]:
A = np.array([[3,5,-2,6], [1,2,-1,1], [2,4,1,5], [3,7,5,3]])
A

array([[ 3,  5, -2,  6],
       [ 1,  2, -1,  1],
       [ 2,  4,  1,  5],
       [ 3,  7,  5,  3]])

In [33]:
adjoint_maxtix(A)

array([[-5.4000000e+01,  7.8000000e+01,  6.0000000e+01, -1.8000000e+01],
       [ 2.4000000e+01, -4.2000000e+01, -2.4000000e+01,  6.0000000e+00],
       [-3.0000000e+00,  1.2000000e+01,  3.0000000e+00, -3.0000000e+00],
       [ 3.0000000e+00,  5.6621374e-15, -9.0000000e+00,  3.0000000e+00]],
      dtype=float32)

In [34]:
np.linalg.det(A)

-18.000000000000014

In [35]:
n = 4
np.linalg.det(A) * np.eye(n,n)

array([[-18.,  -0.,  -0.,  -0.],
       [ -0., -18.,  -0.,  -0.],
       [ -0.,  -0., -18.,  -0.],
       [ -0.,  -0.,  -0., -18.]])

In [36]:
A = np.array([[3,-2,1], [5,6,2], [1,0,-3]])
A

array([[ 3, -2,  1],
       [ 5,  6,  2],
       [ 1,  0, -3]])

In [37]:
np.linalg.det(A)

-94.00000000000007

In [38]:
A.dot(adjoint_maxtix(A))

array([[-94.,   0.,   0.],
       [  0., -94.,   0.],
       [  0.,   0., -94.]])

In [39]:
A = np.array([[ 3,  5, -2,  6],
        [ 1,  2, -1,  1],
        [ 2,  4,  1,  5],
        [ 3,  7,  5,  3]])

In [40]:
np.linalg.det(A)

-18.000000000000014

### 크래머 공식

<img src="cramer-n.jpg" width="500">

다음 연립방정식을 풀어라.  
$-2x_1 + 3x_2 - x_3 = 1$  
$x_1 + 2x_2 - x_3 = 4$  
$-2x_1 - x_2 + x_3 = -3$

In [41]:
A = np.array([[-2, 3, -1], [1, 2, -1], [-2, -1, 1]])
b = np.array([1,4,-3])
print(A)
print(b)

detA = np.linalg.det(A)
detA

[[-2  3 -1]
 [ 1  2 -1]
 [-2 -1  1]]
[ 1  4 -3]


-1.9999999999999998

In [44]:
A1 = A.copy()
A2 = A.copy()
A3 = A.copy()

A1[:, 0] = b  # 첫번째 column 을 b 로 바꿈
A2[:, 1] = b  # 두번째 column 을 b 로 바꿈
A3[:, 2] = b  # 세번째 column 을 b 로 바꿈

print(A1)
print()
print(A2)
print()
print(A3)

[[ 1  3 -1]
 [ 4  2 -1]
 [-3 -1  1]]

[[-2  1 -1]
 [ 1  4 -1]
 [-2 -3  1]]

[[-2  3  1]
 [ 1  2  4]
 [-2 -1 -3]]


In [45]:
print('x1', np.linalg.det(A1) / np.linalg.det(A))
print('x2', np.linalg.det(A2) / np.linalg.det(A))
print('x3', np.linalg.det(A3) / np.linalg.det(A))

x1 2.000000000000001
x2 3.0000000000000018
x3 3.9999999999999996


3x - 3y -2z = 3  
-x - 4y +2z = 2  
5x + 4y + z = 1

In [46]:
A = np.array([[3, -3, -2], [-1, -4, 2], [5, 4, 1]])
b = [3,2,1]

print(A)
print(b)

A1 = A.copy()
A2 = A.copy()
A3 = A.copy()

A1[:, 0] = b
A2[:, 1] = b
A3[:, 2] = b

[[ 3 -3 -2]
 [-1 -4  2]
 [ 5  4  1]]
[3, 2, 1]


In [48]:
print('x = ', np.linalg.det(A1) / np.linalg.det(A))
print('y = ', np.linalg.det(A2) / np.linalg.det(A))
print('z = ', np.linalg.det(A3) / np.linalg.det(A))

x =  0.5940594059405937
y =  -0.544554455445544
z =  0.20792079207920797


### 평행사변형의 면적 = vector 2 개의 determinant

### 평행육면체의 부피 = vector 3 개의 determinant

In [49]:
c1 = np.array([1,1,2])
c2 = np.array([0,2,1])
c3 = np.array([-1,2,2])

A = np.column_stack([c1, c2, c3])
print(A)
print()
print(np.linalg.det(A))

[[ 1  0 -1]
 [ 1  2  2]
 [ 2  1  2]]

4.999999999999999


### 고유값과 고유벡터


w, v = np.linalg.eig(A)  
w : eigenvalue  
v : eigenvector    
The normalized (unit “length”) eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].

In [59]:
A = np.matrix('5 -6;2 -2')
print(A)  
print()
w, v = np.linalg.eig(A)
print(w)
print("when w = ", w[0])
print(v[:, 0])
print("when w = ", w[1])
print(v[:, 1])

[[ 5 -6]
 [ 2 -2]]

[2. 1.]
when w =  2.0000000000000018
[[0.89442719]
 [0.4472136 ]]
when w =  0.9999999999999987
[[0.83205029]
 [0.5547002 ]]


In [63]:
A = np.array([[1, -3], [-3, 1]])
print(A)
print()
w, v = np.linalg.eig(A)
print(w)
print("when w = ", w[0])
print(v[:, 0])
print("when w = ", w[1])
print(v[:, 1])

[[ 1 -3]
 [-3  1]]

[ 4. -2.]
when w =  3.9999999999999996
[ 0.70710678 -0.70710678]
when w =  -2.000000000000001
[0.70710678 0.70710678]


In [65]:
A = np.array([[1,2,2], [1,2,-1], [3,-3,0]])
print(A)
print()
w, v = np.linalg.eig(A)
print(w)
print("when w = ", w[0])
print(v[:, 0])
print("when w = ", w[1])
print(v[:, 1])
print("when w = ", w[2])
print(v[:, 2])

[[ 1  2  2]
 [ 1  2 -1]
 [ 3 -3  0]]

[ 3. -3.  3.]
when w =  3.0
[0.78446454 0.19611614 0.58834841]
when w =  -3.0
[ 0.53452248 -0.26726124 -0.80178373]
when w =  3.0000000000000004
[ 0.06615243 -0.67170594  0.73785838]


In [67]:
# 예제 6 - 삼각행렬의 경우는 주대각선 성분이 고유값이다.
A = np.array([[2,0,0], [-1,-1,0], [0,1,3]])
print(A)
print()
w, v = np.linalg.eig(A)
print(w)
print("when w = ", w[0])
print(v[:, 0])
print("when w = ", w[1])
print(v[:, 1])
print("when w = ", w[2])
print(v[:, 2])

[[ 2  0  0]
 [-1 -1  0]
 [ 0  1  3]]

[ 3. -1.  2.]
when w =  3.0
[0. 0. 1.]
when w =  -1.0
[ 0.          0.9701425  -0.24253563]
when w =  2.0
[ 0.90453403 -0.30151134  0.30151134]


In [68]:
np.linalg.det(np.array([[-3,5,1], [1,0,-2], [0,3,0]]))

-15.000000000000007

In [69]:
np.linalg.det(np.array([[1,0,1,0], [2,1,0,-1], [4,0,1,1], [3,0,1,1]]))

-0.9999999999999998

In [70]:
A = np.array([[1,0,2], [0,5,0], [3,0,4]])
B = np.array([[1,2,0], [3,4,0],[0,0,5]])
np.linalg.det(A.dot(B))

99.99999999999987