# Chapter 3. 행렬연산 (Matrix Operation)

In [86]:
import numpy as np

A = np.array([[1,2,-4], [-2,1,3]])
B = np.array([[0,1,4], [-1,3,1]])
C = np.array([[1,1], [2,2]])

print(A + B)
print(2 * A)
print((-1)*C)

[[ 1  3  0]
 [-3  4  4]]
[[ 2  4 -8]
 [-4  2  6]]
[[-1 -1]
 [-2 -2]]


## 행렬의 곱셈 (Matrix Mulitplication)

In [26]:
A = np.array([[1,2,-1], [3,1,0]])
B = np.array([[-2,1], [0,-3], [2,1]])
np.matmul(A, B)

array([[-4, -6],
       [-6,  0]])

In [27]:
A = np.array([[5,2,3], [-2,-3,4]])
B = np.array([[1,0,1,0], [0,2,2,2], [3,0,-1,3]])
C = np.array([[1,0], [2,-3], [2,1]])
D = np.array([[-1,0], [2,3]])
E = np.array([[1,2], [3,0]])

#### 곱셈의 교환법칙은 일반적으로 성립하지 않는다.

In [28]:
print(np.matmul(D, E))
print(np.matmul(E, D))

[[-1 -2]
 [11  4]]
[[ 3  6]
 [-3  0]]


#### 단위행렬

In [29]:
A = np.array([[4,-2,3], [5,0,2]])
I2 = np.array([[1, 0], [0, 1]])
I3 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [30]:
print(np.matmul(I2, A))
print(np.array_equal(np.matmul(I2, A), A))
print(np.matmul(A, I3))
print(np.array_equal(np.matmul(A, I3), A))

[[ 4 -2  3]
 [ 5  0  2]]
True
[[ 4 -2  3]
 [ 5  0  2]]
True


#### 행렬의 거듭제곱 (power)

In [31]:
A = np.array([[4, -2], [5, 0]])
print(np.linalg.matrix_power(A, 2))
print(np.linalg.matrix_power(A, 3))        # 실수의 거듭제곱과 같은 형식
print(np.linalg.matrix_power(A, 0))       # 지수가 0 이면 단위행렬 생성 (정의)
print(np.array_equal(np.linalg.matrix_power(np.linalg.matrix_power(A, 2), 3), np.linalg.matrix_power(A, 6)))  # 지수법칙 성립

[[  6  -8]
 [ 20 -10]]
[[-16 -12]
 [ 30 -40]]
[[1 0]
 [0 1]]
True


#### 전치행렬

In [32]:
A = np.array([[1,-2,3], [4,5,0]])
B = np.array([[1,2,-4], [3,-1,2], [0,5,3]])
C = np.array([[5, 4], [-3, 2], [2, 1]])
D = np.array([[3, 0, 1]])
E = np.array([[2], [0], [-3]])

In [35]:
print(A)
print(B)
print(C)
print(D)
print(E)

[[ 1 -2  3]
 [ 4  5  0]]
[[ 1  2 -4]
 [ 3 -1  2]
 [ 0  5  3]]
[[ 5  4]
 [-3  2]
 [ 2  1]]
[[3 0 1]]
[[ 2]
 [ 0]
 [-3]]


In [36]:
print(np.transpose(A))
print(B.T)
print(C.T)
print(D.T)
print(np.transpose(E))

[[ 1  4]
 [-2  5]
 [ 3  0]]
[[ 1  3  0]
 [ 2 -1  5]
 [-4  2  3]]
[[ 5 -3  2]
 [ 4  2  1]]
[[3]
 [0]
 [1]]
[[ 2  0 -3]]


#### $(AB)^T = B^T A^T$

In [37]:
A = np.array([[1,3], [2,5]])
B = np.array([[1, 1, 3], [2, 1, 4]])
AB = np.matmul(A, B)
np.array_equal(AB.T, np.matmul(B.T, A.T))

True

#### 대각합(trace) : tr(AB) = tr(BA)  --> 주대각선 성분의 합은 같다

In [43]:
A = np.array([[1, -2], [4, 5]])
B = np.array([[5, 4], [-3, 2]])
print(A)
print(B)
print()
print(A.dot(B))
print(B.dot(A))
np.array_equal(np.trace(A.dot(B)), np.trace(B.dot(A)))

[[ 1 -2]
 [ 4  5]]
[[ 5  4]
 [-3  2]]

[[11  0]
 [ 5 26]]
[[21 10]
 [ 5 16]]


True

#### 역행렬

In [45]:
A = np.array([[3, 5], [1, 2]])
B = np.array([[1,3], [2,7]])
print(A)
print(B)
print()
print(np.linalg.inv(np.matmul(A, B)))
print(np.matmul(np.linalg.inv(B), np.linalg.inv(A)))

[[3 5]
 [1 2]]
[[1 3]
 [2 7]]

[[ 17. -44.]
 [ -5.  13.]]
[[ 17. -44.]
 [ -5.  13.]]


In [47]:
A = np.array([[1,2,3], [2,5,3], [1,0,8]])
print(A)
print(np.linalg.inv(A))

[[1 2 3]
 [2 5 3]
 [1 0 8]]
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


In [48]:
A = np.array([[1, 6, 4], [2, 4, -1], [-1, 2, 5]])
np.linalg.inv(A)

LinAlgError: Singular matrix

In [49]:
A = np.array([[1, -1, 2], [-1, 0, 2], [-6, 4, 11]])
print(A)
np.linalg.inv(A)

[[ 1 -1  2]
 [-1  0  2]
 [-6  4 11]]


array([[ 0.53333333, -1.26666667,  0.13333333],
       [ 0.06666667, -1.53333333,  0.26666667],
       [ 0.26666667, -0.13333333,  0.06666667]])

### 만일 A 가 가역행렬이면, $A^T$ 도 가역행렬이고 다음이 성립한다.
$$ (A^T)^{-1} = (A^{-1})^T$$

In [57]:
# 예제 4
A = np.array([[3, 5], [1, 2]])
B = np.array([[1, 3], [2, 7]])
print(A)
print(B)
print()
print(np.linalg.inv(A.dot(B)))
print(np.linalg.inv(B).dot(np.linalg.inv(A)))

[[3 5]
 [1 2]]
[[1 3]
 [2 7]]

[[ 17. -44.]
 [ -5.  13.]]
[[ 17. -44.]
 [ -5.  13.]]


In [59]:
#예제 4 다음행렬의 역행렬

A = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
print(A)
np.linalg.inv(A)

[[1 2 3]
 [2 5 3]
 [1 0 8]]


array([[-40.,  16.,   9.],
       [ 13.,  -5.,  -3.],
       [  5.,  -2.,  -1.]])

In [60]:
#예제 5 역행렬구하기
A = np.array([[1, -1, 2], [-1, 0, 2], [-6, 4, 11]])
print(A)
np.linalg.inv(A)

[[ 1 -1  2]
 [-1  0  2]
 [-6  4 11]]


array([[ 0.53333333, -1.26666667,  0.13333333],
       [ 0.06666667, -1.53333333,  0.26666667],
       [ 0.26666667, -0.13333333,  0.06666667]])

### 3.5 선형연립방정식의 해집합과 행렬

In [65]:
# 예제 1
# Ax = b 에서 유일한 해를 구하라
import numpy as np

A = np.matrix([[1,2,3], [2,5,3], [1,0,8]])
b = np.matrix([1,3,-1])
print(A)
print(b)

[[1 2 3]
 [2 5 3]
 [1 0 8]]
[[ 1  3 -1]]


In [66]:
# x = A^(-1) b --> 유일한 해
np.linalg.inv(A).dot(b.T)

matrix([[-1.0000000e+00],
        [ 1.0000000e+00],
        [-4.4408921e-16]])

In [70]:
#예제 2 
# 대각선행렬의 거듭제곱은 주대각선성분을 거듭제곱한 대각선 행렬과 같다
D = np.diag([1, -3, 2])
print(D)
print(D**5)

[[ 1  0  0]
 [ 0 -3  0]
 [ 0  0  2]]
[[   1    0    0]
 [   0 -243    0]
 [   0    0   32]]


In [75]:
A = np.matrix('1 2 3;2 4 5;3 5 6')
B = np.matrix('0 1 -2; -1 0 3; 2 -3 0')
I3 = np.matrix('1 0 0;0 1 0;0 0 1')
print(A)
print(B)
print(I3)

[[1 2 3]
 [2 4 5]
 [3 5 6]]
[[ 0  1 -2]
 [-1  0  3]
 [ 2 -3  0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [76]:
A.T == A

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [79]:
B.T == -B

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

## LU 분해 (LU decomposition)

In [85]:
import scipy.linalg as la

A = np.array([[1,1,2], [2,4,-3], [3,6,-5]])
la.lu(A)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 3.33333333e-01,  1.00000000e+00,  0.00000000e+00],
        [ 6.66666667e-01, -2.22044605e-16,  1.00000000e+00]]),
 array([[ 3.        ,  6.        , -5.        ],
        [ 0.        , -1.        ,  3.66666667],
        [ 0.        ,  0.        ,  0.33333333]]))

### 연습문제

In [18]:
A = np.array([[1, 3], [4, -1]])
B = np.array([[-1, 2, 5], [1, -1, 4]])
C = np.array([[1, 0], [2, -1], [3, 2]])

print(A.dot(np.matmul(B, C)))
print(np.matmul(A, B).dot(C))

[[51 35]
 [61 23]]
[[51 35]
 [61 23]]


In [19]:
A = np.array([[-2, 3], [2, -3]])
B = np.array([[-1, 3], [2, 0]])
C = np.array([[-4, -3], [0, -4]])

print(np.matmul(A, B))
print(np.matmul(A, C))

[[ 8 -6]
 [-8  6]]
[[ 8 -6]
 [-8  6]]


In [25]:
A = np.array([[1, 3], [4, -1]])

3 * np.linalg.matrix_power(A, 3) - 2 * np.linalg.matrix_power(A, 2) + 5 * A - 4 * np.eye(2)

array([[ 14., 132.],
       [176., -74.]])

In [28]:
A = np.array([[1,1,2], [2,4,-3],[3,6,-5]])
b = np.array([[2, -17, 11], [-1, 11, -7], [0, 3, -2]])

print(np.linalg.inv(np.transpose(A)))
print(np.transpose(np.linalg.inv(A)))

[[ 2.0000000e+00 -1.0000000e+00  4.4408921e-16]
 [-1.7000000e+01  1.1000000e+01  3.0000000e+00]
 [ 1.1000000e+01 -7.0000000e+00 -2.0000000e+00]]
[[ 2.00000000e+00 -1.00000000e+00  6.66133815e-16]
 [-1.70000000e+01  1.10000000e+01  3.00000000e+00]
 [ 1.10000000e+01 -7.00000000e+00 -2.00000000e+00]]
