# 1. Basic Numpy

In [2]:
import sys
import numpy as np

print("python {}".format(sys.version))
print("numpy {}".format(np.__version__))

python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy 1.15.0


In [3]:
# 스칼라
x = 6
x

6

In [4]:
# 벡터
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
print("vector dimension {}".format(x.shape))
print("vector size {}".format(x.size))

vector dimension (3,)
vector size 3


In [9]:
# 매트릭스
x = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
print("matrix dimension {}".format(x.shape))
print("matrix size {}".format(x.size))

matrix dimension (3, 3)
matrix size 9


In [12]:
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))

array dimension (3, 3)
array size 9


np.matrix 는 2 dimensional array 만 support 하고 np.array 는 임의의 n-dimensional array 를 모두 support 하므로 두가지를 섞어서 사용하면 혼돈스럽게 되므로 np.array 로 통일하여 사용하는 것이 좋다.

matrix 는 a*b 가 matrix multiplication 이고, ndarray 는 a*b 가 element-wise multiplication 이다. ndarray 는 a@b 혹은 np.dot(a,b) 혹은 a.dot(b) 가 matrix multiplication 이다.

In [15]:
# 주어진 dimension 의 matrix 정의
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
print("array dimension {}".format(x.shape))
print("array size {}".format(x.size))

array dimension (2, 3)
array size 6


In [17]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
print("array dimension {}".format(x.shape))
print("array size {}".format(x.size))

array dimension (3, 3, 3)
array size 27


In [20]:
# indexing matrix
A = np.ones((5,5), dtype=np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
A[0]

array([1, 1, 1, 1, 1])

In [24]:
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
A[:, 0] = 3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [27]:
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [31]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, :, 0] = 3
A

array([[[3, 0, 0],
        [3, 0, 0],
        [3, 0, 0]],

       [[3, 0, 0],
        [3, 0, 0],
        [3, 0, 0]],

       [[3, 0, 0],
        [3, 0, 0],
        [3, 0, 0]]])

In [33]:
A = np.zeros((3,3,3), dtype=np.int)
A[0, :, :] = 3
A

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [34]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, 0, :] = 3
A

array([[[3, 3, 3],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 3, 3],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 3, 3],
        [0, 0, 0],
        [0, 0, 0]]])

In [35]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, 0, 0] = 3
A

array([[[3, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [42]:
# matrix operation
a = np.array([[1,2], [3,4]])
b = np.ones((2,2), dtype=np.int)
a + b

array([[2, 3],
       [4, 5]])

In [43]:
a * b

array([[1, 2],
       [3, 4]])

In [44]:
a - b

array([[0, 1],
       [2, 3]])

In [45]:
np.matmul(a, b)

array([[3, 3],
       [7, 7]])

In [46]:
a@b

array([[3, 3],
       [7, 7]])

In [47]:
a.dot(b)

array([[3, 3],
       [7, 7]])

In [49]:
# matrix transpose
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [54]:
A = np.array(range(10)).reshape((2,5))
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
B = A.T
B

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [56]:
print(A.shape)
print(B.shape)

(2, 5)
(5, 2)


In [65]:
# tensors
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A))
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
3
10
59049
