In [1]:
import numpy as np

In [5]:
a = np.array([[5]])
np.linalg.det(a)

4.999999999999999

In [6]:
b = np.array([[3,1], [4,-2]])
np.linalg.det(b)

-10.000000000000002

In [7]:
c = np.array([[1,2,3], [-4,5,6], [7,-8,9]])
np.linalg.det(c)

240.0000000000002

### $A 와 A^T$ 의 determinant 는 같다

In [10]:
d = c.T
np.linalg.det(d)

239.99999999999997

### 행렬 B 가 정사각행렬 A 의 두행(열)을 서로 바꾸어 얻어진 행렬이라면, |B| = -|A| 이다.

In [12]:
A = np.array([[2, -1], [3,2]])
B = np.array([[3,2], [2,-1]])
print(np.linalg.det(A))
print(np.linalg.det(B))

6.999999999999999
-6.999999999999999


In [13]:
A = np.array([[2, -1], [3,2]])
B = np.array([[-1, 2], [2,3]])
print(np.linalg.det(A))
print(np.linalg.det(B))

6.999999999999999
-7.000000000000001


### 정사각행렬 A 의 두행(열)이 일치하면 |A| = 0 이다.

In [14]:
A = np.array([[1,2,3], [-1,0,7], [1,2,3]])
np.linalg.det(A)

0.0

In [15]:
A = np.array([[1,2,1], [-1,0,-1], [1,2,1]])
np.linalg.det(A)

0.0

### 정사각행렬 A 의 한 행(열)의 성분이 모두 0 이면 |A| = 0

In [17]:
A = np.array([[1,2,3], [4,5,6], [0,0,0]])
np.linalg.det(A)

0.0

### 정사각행렬 A 의 한 행을 k(상수) 배하여 얻어진 행렬을 B 라 하면 |B| = k|A| 인 관계가 성립하는 |A| 는 0 이다.

In [21]:
A = np.array([[1,2,3], [1,5,3], [2,8,6]])
B = np.array([[1,2,3], [1,5,3], [1,4,3]])  # |A| = 2 * |B|
C = np.array([[1,2,1], [1,5,1], [1,1,1]])  # |A| = 2 * 3 * |C|
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(C))

0.0
0.0
0.0


### 정사각행렬 A 의 한 행의 k 배를 다른 행에 더하여 얻어진 행렬을 B 라 하면 |B| = |A| 이다.

In [26]:
A = np.array([[1,2,3], [2,-1,3], [1,0,1]])  # 2 행을 1 배 하여 1 행에 더함
B = np.array([[5,0,9], [2,-1,3], [1,0,1]]) 
print(np.linalg.det(A))
print(np.linalg.det(B))

4.000000000000001
4.0


### A 가 n 차의 삼각행렬이면 A 의 행렬식은 주대각성분의 곱과 같다.

In [50]:
A = np.array([[2,7,-3,8,3], [0,-3,7,5,1], [0,0,6,7,6], [0,0,0,9,8], [0,0,0,0,4]])
A

array([[ 2,  7, -3,  8,  3],
       [ 0, -3,  7,  5,  1],
       [ 0,  0,  6,  7,  6],
       [ 0,  0,  0,  9,  8],
       [ 0,  0,  0,  0,  4]])

In [51]:
print(np.linalg.det(A))
print([x for x in np.diag(A)])

from functools import reduce
reduce(lambda x, y: x*y, [x for x in np.diag(A)])

-1295.9999999999998
[2, -3, 6, 9, 4]


-1296

### 두행렬 A, B 가 n 차의 정사각행렬일 때 |AB| = |A||B| 이다.

In [56]:
A = np.array([[1,2], [3,4]])
B = np.array([[2,-1], [1,2]])
print(np.linalg.det(np.matmul(A, B)))
print(np.linalg.det(A) * np.linalg.det(B))

-10.000000000000002
-10.000000000000004


### 행렬 A 가 가역이면 |A|$\neq$0 이고, $|A^{-1}|$= $\frac{1}{|A|}$ 이 성립한다.

In [58]:
A = np.array([[1,2], [3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
print(1 / np.linalg.det(A))
np.linalg.det(np.linalg.inv(A))

-0.4999999999999999


-0.5000000000000001

### 부분행렬

In [200]:
x = np.array([[3,1,-4],[2,5,6],[1,4,8]] , dtype = 'int')

# 부분행렬
def partialMatrix(arr, row, col):
    row -= 1
    col -= 1
    adjointArr = np.zeros((arr.shape[0]-1, arr.shape[1]-1))
    r, c = 0, 0
    for i in range(len(arr)):
        if i != row:
            for j in range(len(arr)):
                if j != col:
                    adjointArr[r][c] = arr[i][j]
                    c += 1
            r += 1
            c = 0   
    return adjointArr

In [201]:
partialMatrix(x, 1, 2)

array([[2., 6.],
       [1., 8.]])

In [202]:
partialMatrix(x, 1,1)

array([[5., 6.],
       [4., 8.]])

### 소행렬식 / 여인자


In [203]:
# 소행렬식
M11 = np.linalg.det(partialMatrix(x, 1, 1))
M11

15.999999999999998

In [204]:
# 여인자
A11 = (-1) ** (1+1) * M11
A11

15.999999999999998

In [205]:
def cofactor(partial, row, col):
    return (-1) ** (row + col) * np.linalg.det(partial)

In [206]:
cofactor(partialMatrix(x, 1, 1), 1, 1)

15.999999999999998

In [207]:
cofactor(partialMatrix(x, 1, 2), 1, 2)

-9.999999999999998

### 수반행렬

In [208]:
import numpy as np
x = np.array([[3,-2,1],[5,6,2],[1,0,-3]])

c = np.array([[i for i in range(3)] for j in range(3)], dtype='float32')  # 수반행렬
for i in range(3):
    for j in range(3):
        c[i][j] = cofactor(partialMatrix(x, i+1, j+1), i+1, j+1)

In [209]:
x

array([[ 3, -2,  1],
       [ 5,  6,  2],
       [ 1,  0, -3]])

In [210]:
partialMatrix(x, 1, 1)

array([[ 6.,  2.],
       [ 0., -3.]])

In [211]:
cofactor(partialMatrix(x, 1, 1), 1, 1)

-17.999999999999996

In [212]:
c

array([[-18.,  17.,  -6.],
       [ -6., -10.,  -2.],
       [-10.,  -1.,  28.]], dtype=float32)

In [213]:
A = np.array([[3,5,-2,6], [1,2,-1,1], [2,4,1,5], [3,7,5,3]])
A

array([[ 3,  5, -2,  6],
       [ 1,  2, -1,  1],
       [ 2,  4,  1,  5],
       [ 3,  7,  5,  3]])

In [214]:
np.linalg.det(A)

-18.000000000000014

In [217]:
np.linalg.det(A) * np.eye(n,n)

array([[-18.,  -0.,  -0.,  -0.],
       [ -0., -18.,  -0.,  -0.],
       [ -0.,  -0., -18.,  -0.],
       [ -0.,  -0.,  -0., -18.]])

In [219]:
A = np.array([[3,-2,1], [5,6,2], [1,0,-3]])

In [220]:
np.linalg.inv(A)

array([[ 0.19148936,  0.06382979,  0.10638298],
       [-0.18085106,  0.10638298,  0.0106383 ],
       [ 0.06382979,  0.0212766 , -0.29787234]])